services:
  app:
    build: ./app
    restart: always
    ports:
      - "80:80"
      - "2222:2222"

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
