interface SpecRef {
  /** Object name as written in the spec, e.g. "Task". */
  name: string;
  /** Tooltip category, e.g. "Core object". */
  kind: string;
  /** a2a-specs.md section number. */
  section: string;
  /** Display override for the node's type label. */
  type?: string;
  /** Display type for elements of an array of spec objects. */
  itemType?: string;
  /** Prose description copied from a2a-specs.md, shown in the popover. */
  description?: string;
  /** Child keys that must not inherit a spec lookup (e.g. error.message). */
  ignore?: string[];
}

/**
 * Spec-highlighted objects keyed by payload label, derived from a2a-specs.md.
 * Core objects: §4.1/4.2. Operation parameter objects: §3.1/3.2/9.4.
 */
const specObjects: Record<string, SpecRef> = {
  // 4.1 Core Objects
  task: {
    name: "Task",
    kind: "Core object",
    section: "4.1.1",
    type: "Task",
    description:
      "The fundamental unit of work managed by A2A, identified by a unique ID. Tasks are stateful and progress through a defined lifecycle.",
  },
  status: {
    name: "TaskStatus",
    kind: "Core object",
    section: "4.1.2",
    type: "TaskStatus",
    description:
      "The current status of a Task, containing its TaskState, a timestamp, and an optional Message describing the state.",
  },
  state: {
    name: "TaskState",
    kind: "Core object",
    section: "4.1.3",
    type: "TaskState",
    description:
      "The lifecycle state of a Task, progressing through active states (submitted, working) and interrupted states (input-required, auth-required) to terminal states (completed, failed, canceled, rejected).",
  },
  message: {
    name: "Message",
    kind: "Core object",
    section: "4.1.4",
    type: "Message",
    description:
      'A communication turn between a client and a remote agent, having a `role` ("user" or "agent") and containing one or more `Parts`.',
  },
  role: {
    name: "Role",
    kind: "Core object",
    section: "4.1.5",
    type: "Role",
    description:
      'Indicates whether the sender of a Message is the client ("user") or the remote agent ("agent").',
  },
  parts: {
    name: "Part",
    kind: "Core object",
    section: "4.1.6",
    type: "Part[]",
    itemType: "Part",
    description:
      "The smallest unit of content within a Message or Artifact. Parts can contain text, file references, or structured data.",
  },
  artifact: {
    name: "Artifact",
    kind: "Core object",
    section: "4.1.7",
    type: "Artifact",
    description:
      "An output (e.g., a document, image, structured data) generated by the agent as a result of a task, composed of `Parts`.",
  },
  artifacts: {
    name: "Artifact",
    kind: "Core object",
    section: "4.1.7",
    type: "Artifact[]",
    itemType: "Artifact",
    description:
      "An output (e.g., a document, image, structured data) generated by the agent as a result of a task, composed of `Parts`.",
  },
  history: {
    name: "Message",
    kind: "Core object",
    section: "4.1.4",
    type: "Message[]",
    itemType: "Message",
    description:
      'A communication turn between a client and a remote agent, having a `role` ("user" or "agent") and containing one or more `Parts`.',
  },
  statusupdate: {
    name: "TaskStatusUpdateEvent",
    kind: "Core object",
    section: "4.2.1",
    type: "TaskStatusUpdateEvent",
    description:
      "An event sent over a stream when the status of a Task changes, carrying the updated TaskStatus. The stream MUST close when the task reaches a terminal state.",
  },
  artifactupdate: {
    name: "TaskArtifactUpdateEvent",
    kind: "Core object",
    section: "4.2.2",
    type: "TaskArtifactUpdateEvent",
    description:
      "An event sent over a stream when an Artifact is created or updated for a Task, with append and lastChunk flags controlling chunked artifact delivery.",
  },
  // 3.1/3.2 Operation request and response objects
  sendmessagerequest: {
    name: "SendMessageRequest",
    kind: "Operation parameter object",
    section: "3.2.1",
    type: "SendMessageRequest",
    description:
      "The parameters for the Send Message operation: the Message to send, plus optional tenant, configuration, and metadata.",
  },
  gettaskrequest: {
    name: "GetTaskRequest",
    kind: "Operation parameter object",
    section: "3.1.3",
    type: "GetTaskRequest",
    description:
      "Retrieves the current state (including status, artifacts, and optionally history) of a previously initiated task.",
  },
  canceltaskrequest: {
    name: "CancelTaskRequest",
    kind: "Operation parameter object",
    section: "3.1.5",
    type: "CancelTaskRequest",
    description:
      "Requests the cancellation of an ongoing task. The server will attempt to cancel the task, but success is not guaranteed.",
  },
  sendmessageresponse: {
    name: "SendMessageResponse",
    kind: "Operation parameter object",
    section: "9.4.1",
    type: "SendMessageResponse",
    description: "The response to SendMessage, contains one of: a Task object or a Message object.",
  },
  streamresponse: {
    name: "StreamResponse",
    kind: "Operation parameter object",
    section: "3.2.3",
    type: "StreamResponse",
    description:
      "This wrapper allows streaming endpoints to return different types of updates through a single response stream while maintaining type safety.",
  },
  configuration: {
    name: "SendMessageConfiguration",
    kind: "Operation parameter object",
    section: "3.2.2",
    type: "SendMessageConfiguration",
    description:
      "Controls the execution mode of SendMessage. The return_immediately field controls whether the operation returns immediately or waits for task completion; operations are blocking by default.",
  },
  metadata: {
    name: "Metadata",
    kind: "Operation parameter object",
    section: "3.2.5",
    type: "Metadata",
    description:
      "A flexible key-value map for passing additional context or parameters with operations. Metadata keys must be strings, and values can be any valid JSON value.",
  },
  // Well-known or scalar spec types without object semantics
  timestamp: { name: "Timestamp", kind: "", section: "", type: "timestamp" },
  acceptedoutputmodes: { name: "", kind: "", section: "", type: "string[]" },
  historylength: { name: "", kind: "", section: "", type: "integer" },
  // JSON-RPC error payloads: `message` is a plain string, not a Message object
  error: { name: "", kind: "", section: "", ignore: ["message"] },
};

function valueType(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) return `array · ${value.length}`;
  return typeof value;
}

interface PopoverState {
  anchor: HTMLElement;
  el: HTMLDivElement;
  pinned: boolean;
}

const livePopovers = new Set<PopoverState>();
const anchorStates = new WeakMap<HTMLElement, PopoverState>();

function positionPopover(state: PopoverState): void {
  const rect = state.anchor.getBoundingClientRect();
  const el = state.el;
  const left = Math.max(8, Math.min(rect.left, window.innerWidth - el.offsetWidth - 8));
  const top = Math.max(8, Math.min(rect.bottom + 6, window.innerHeight - el.offsetHeight - 8));
  el.style.left = `${left}px`;
  el.style.top = `${top}px`;
}

function showPopover(state: PopoverState): void {
  if (!state.el.isConnected) {
    document.body.append(state.el);
    livePopovers.add(state);
  }
  positionPopover(state);
}

function hidePopover(state: PopoverState): void {
  state.el.remove();
  livePopovers.delete(state);
}

function buildPopover(
  name: string,
  kind: string,
  section: string,
  description?: string,
): HTMLDivElement {
  const box = document.createElement("div");
  box.className =
    "fixed z-50 w-80 max-w-[calc(100vw-1rem)] rounded-xl border border-stone-200 bg-white p-3 text-left shadow-lg dark:border-slate-700 dark:bg-slate-900";
  const heading = document.createElement("p");
  heading.className = "font-mono text-xs font-bold text-violet-700 dark:text-violet-300";
  heading.textContent = `${name} (${kind} ${section})`;
  box.append(heading);
  if (description) {
    const body = document.createElement("p");
    body.className = "mt-1.5 text-xs leading-relaxed text-stone-600 dark:text-slate-300";
    body.textContent = description;
    box.append(body);
  }
  return box;
}

function makeNode(label: string, value: unknown, depth = 0, ctx?: SpecRef): HTMLElement {
  const spec = ctx ?? specObjects[label.toLowerCase()];
  const typeDisplay = spec?.type ?? valueType(value);
  const node = document.createElement("div");
  node.className =
    depth === 0
      ? "rounded-xl border-2 border-stone-300 bg-stone-50 p-3 transition-[filter] dark:border-slate-600 dark:bg-slate-900"
      : "rounded-lg border border-stone-200 bg-white/70 p-2.5 transition-[filter] dark:border-slate-700 dark:bg-slate-950/70";
  node.dataset.treeKind = typeDisplay.split(" · ")[0];
  node.dataset.treeNode = "";
  node.setAttribute("role", "group");
  node.setAttribute("aria-label", `${label}: ${typeDisplay}`);

  const header = document.createElement("div");
  header.className = "flex items-baseline gap-2";

  const name = document.createElement("span");
  name.className = "break-all font-mono text-xs font-bold text-sky-700 dark:text-sky-300";
  name.textContent = label;

  const type = document.createElement("span");
  if (spec?.kind) {
    type.className =
      "cursor-pointer text-xs text-violet-700 underline decoration-dotted underline-offset-2 dark:text-violet-300";
    type.textContent = typeDisplay;

    const state: PopoverState = {
      anchor: type,
      el: buildPopover(spec.name, spec.kind, spec.section, spec.description),
      pinned: false,
    };
    anchorStates.set(type, state);
    type.addEventListener("mouseenter", () => showPopover(state));
    type.addEventListener("mouseleave", () => {
      if (!state.pinned) hidePopover(state);
    });
    type.addEventListener("click", (event) => {
      event.stopPropagation();
      state.pinned = !state.pinned;
      if (state.pinned) showPopover(state);
      else hidePopover(state);
    });
  } else {
    type.className = "text-xs text-stone-500 dark:text-slate-400";
    type.textContent = typeDisplay;
  }
  header.append(name, type);
  node.append(header);

  if (value !== null && typeof value === "object") {
    const children = document.createElement("div");
    children.className = "mt-2 grid gap-2";
    const entries: [string, unknown][] = Array.isArray(value)
      ? value.map((item, index) => [`[${index}]`, item])
      : Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) {
      const empty = document.createElement("span");
      empty.className = "font-mono text-xs italic text-stone-400 dark:text-slate-500";
      empty.textContent = "empty";
      children.append(empty);
    } else {
      children.append(
        ...entries.map(([key, item]) => {
          let childCtx: SpecRef | undefined;
          if (Array.isArray(value) && spec?.itemType) {
            childCtx = {
              name: spec.itemType,
              kind: spec.kind,
              section: spec.section,
              type: spec.itemType,
            };
          } else if (spec?.ignore?.includes(key)) {
            childCtx = { name: "", kind: "", section: "" };
          }
          return makeNode(key, item, depth + 1, childCtx);
        }),
      );
    }
    node.append(children);
    return node;
  }

  const primitive = document.createElement("div");
  primitive.className = `mt-1.5 whitespace-pre-wrap break-words font-mono text-sm ${
    value === null || value === undefined
      ? "italic text-stone-400 dark:text-slate-500"
      : typeof value === "string"
        ? "text-emerald-700 dark:text-emerald-300"
        : typeof value === "boolean"
          ? "text-violet-700 dark:text-violet-300"
          : "text-amber-700 dark:text-amber-300"
  }`;
  primitive.textContent = value === "" ? "(empty string)" : String(value);
  node.append(primitive);
  return node;
}

export function renderDataTree(container: HTMLElement, value: unknown, label: string): void {
  // Drop popovers whose anchors are about to be replaced.
  for (const state of [...livePopovers]) {
    if (!state.anchor.isConnected) {
      state.el.remove();
      livePopovers.delete(state);
    }
  }
  container.replaceChildren(makeNode(label, value));

  // Darken only the innermost box under the cursor; ancestors stay normal.
  if (!container.dataset.treeHoverBound) {
    container.dataset.treeHoverBound = "true";
    const clear = () => {
      for (const node of container.querySelectorAll("[data-tree-node]")) {
        node.classList.remove("brightness-[0.92]");
      }
    };
    container.addEventListener("mouseover", (event) => {
      clear();
      const innermost = (event.target as Element).closest("[data-tree-node]");
      innermost?.classList.add("brightness-[0.92]");
    });
    container.addEventListener("mouseleave", clear);
  }
}

// Keep pinned popovers anchored while scrolling or resizing.
window.addEventListener(
  "scroll",
  () => {
    for (const state of livePopovers) positionPopover(state);
  },
  { passive: true },
);
window.addEventListener("resize", () => {
  for (const state of livePopovers) positionPopover(state);
});
